version: "3.9"
services:
  basket:
    build:
      context: .
      dockerfile: DockerfileBasket
    ports:
      - "801:80"
    depends_on:
      - mssql
  catalog:
    build:
      context: .
      dockerfile: DockerfileCatalog
    ports:
      - "802:80"
    depends_on:
      - mssql
  angular:
    build:
      context: Presentations/AngularUi
      dockerfile: Dockerfile
    ports:
      - "803:80"
    depends_on:
      - basket
      - catalog
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
#    ports:
#      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
